#!/bin/bash -l

#$ -P dl523
#$ -m ea
#$ -N boxes
#$ -j y
#$ -o boxes.out
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_c=6.0

### load your environment and run the job

# example:
module load miniconda
conda activate dl523
python deformable_detr/bulk_box.py
