#!/bin/bash -l

#$ -P dl523
#$ -m ea
#$ -N KMjudo_train
#$ -j y
#$ -o KMtraining_10e.out
#$ -pe omp 8
#$ -l gpus=1
#$ -l gpu_c=7.0

### load your environment and run the job

# example:
module load miniconda
conda activate openmmlab
python km_judo_final.py